### ISSUE TITLE
Derek GM Midterm-slicing.py is ready

### ISSUE THREAD

**Issue by dmargie-matc** [madisoncollege-it-programs/python-scripting-dmargie#10]
I feel like this is the only one I had a handle on, but I could easily have misinterpreted the brief.

**Comment by cethenmc** [comment]
Midterm-slicing:  Pretty creative to get the correct answer.  However, each variable was to be done with a single slice, and you should have sliced by the nature of the hint.  listA you went from the front to get the word instead of the back (2 pt).  listsB throught E you did three slices for each instead of 1 (8 pts).  As a result, you bypassed using joins (2 pts).  22/34
