### ISSUE TITLE
This is my Week 9 Functions assignment

### ISSUE THREAD

**Issue by dmargie-matc** [madisoncollege-it-programs/python-scripting-dmargie#11]

**Comment by cethenmc** [comment]
5 of 8.  Good thinking to add a conversion in each direction.  Points missed, there was no main() function, nor the associated conditional on  \_\_name\_\_ variable.  f2c.py was not tested by calling it directly.  tempconversion.py is not importing from f2c, and the function was reproduced instead of calling to f2c.py.   You can resubmit soon, following the instructions, for full credit.  Thanks.

**Comment by cethenmc** [comment]
![image](https://user-images.githubusercontent.com/112707666/208516984-f139d4e4-b6c2-4967-ba78-b7f1fd8336f5.png)
