### ISSUE TITLE
Derek GM Week 5 File Data Interaction Submission

### ISSUE THREAD

**Issue by dmargie-matc** [madisoncollege-it-programs/python-scripting-dmargie#5]

**Comment by cethenmc** [comment]
Hi, Derek.  You left a print(type(strfiletext)), which was not asked for.  I am impressed you decided to do a write function for this exercise for fun, but the assignment did not require you to write a file.

Your answer for the len() when using the readlines() is accurate, so I will give you full credit.  However, it would have been nice if you related it back to the context of the file.  Meaning, the len() gives the count of lines in the file because each list element is a line from the file.

Finally, the last one, you decided to skip the "save the full file contents one line at a time to a variable" when processing.  

I will add a 6 out of 8 to the grade book and encourage you to clean up, fix the third, and resubmit for full credit.  Please reach out if you have questions.  Thanks. ~Chris

**Comment by cethenmc** [comment]
Locked in the 6 out of 8 and closed ticket.
