### ISSUE TITLE
Submitted Week 7 Dictionaries script

### ISSUE THREAD

**Issue by dmargie-matc** [madisoncollege-it-programs/python-scripting-dmargie#7]

**Comment by cethenmc** [comment]
Hi, Derek.  I really appreciate the creativity and enthusiasm for coding, but please follow the instructions on the assignment.  Save this cool one that you created for your fun under a different name, and perhaps start from scratch using a simple dictionary like this:
dictAddresses = ("server1.testlab.com" : "192.168.1.10", "server2.testlab.com" : "192.168.1.11", ...}

Just because it is cool, and in a round about way answers questions, I will record a 6 of 8 for now.

**Comment by cethenmc** [comment]
Locked in the 6 out of 8 and closed ticket.
