### ISSUE TITLE
Derek GM Midterm-if.py script

### ISSUE THREAD

**Issue by dmargie-matc** [madisoncollege-it-programs/python-scripting-dmargie#8]
I couldn't for the life of me figure out how to work the conversion variable to do what was required.

**Comment by cethenmc** [comment]
All concepts you used were concepts learned in class, which was nice to see.  I like that you analyzed your data carefully to identify the column structure in the flat file.  Perhaps you had to analyze too much to creatively come up with the correct line numbers.  The results should have rendered the correct total, but the total you printed was that of the last line number (2 pts).  Because you took the single characters to extract the line number instead of using a delimiter and converting to int to add to a total, I remove (3 pts).  There were excessive lines printed (1 pt).  Elifs were ignored, as a result, if someone named Kayley Whiteland were listed, you would have added that line twice (2 pts).   Resulting score 25/33.
