### ISSUE TITLE
Derek GM Midterm-jpark.py script

### ISSUE THREAD

**Issue by dmargie-matc** [madisoncollege-it-programs/python-scripting-dmargie#9]
This one had me mostly stumped. I only got about halfway through before it all fell apart.

**Comment by cethenmc** [comment]
Midterm-jpark:  Thanks for putting in an effort on this part of the midterm.  The first part I analyze is program execution.  When I enter false username and password combos, I still get in on the first login, and there are no failure messages as required (6 pts).  Then once I am in, I get name errors with every selection I make.  The name error is the interpreter looking that a variable was assigned a value.  Often this occurs (as is this case), when the author intends for something to be a hardcoded string but forgot to place quotations (4 pts).  Inside the code there is an unnecessary instantiation of empty dictionaries before adding values.  The password_database = dict() and the command_database = dict() steps are unnecessary (1 pt).  In line 30 you hardcoded the printout of the keys instead of supplying them to the user dynamically from the dictionary (2 pts).   In lines 31 -37, you have inconsistencies between the evaluation of the first option and the other two, as I think you may have been trying to get it to work.  However, each of those methods would not be pulled from the dictionary, and could be consolidated into one if (2 pts).  The input is not assigned to a variable, and so you are not getting anything back to use from the user to evaluate against (2 pts).  Finally, you commented out the else with the Lysine Contingency clause and that was the part of that flow logic that was correct (1 pt).  15/33
